send:
  name: Send Notification
  description: Send a notification via OpenNotification server.
  fields:
    title:
      description: Title of the notification
      example: Home Assistant
    description:
      description: Body text
      example: Someone is at the door!
    pictureLink:
      description: Optional picture link
      example: https://example.com/image.jpg
    icon:
      description: Optional icon
      example: https://example.com/icon.jpg
    actionLink:
      description: Optional action link
      example: homeassistant://navigate/lovelace/kiosk-camera
    isAlert:
      description: Whether this is an alert
      example: true
